/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import proyectofinal.Login;

/**
 *
 * @author Luzmi
 */
public class administrador extends javax.swing.JFrame {
    

    /**
     * Creates new form administrador
     */
    public administrador() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCandidatos = new javax.swing.JButton();
        btnElecciones = new javax.swing.JButton();
        btnElecciones1 = new javax.swing.JButton();
        btn_Menu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        btnCandidatos.setBackground(new java.awt.Color(0, 153, 51));
        btnCandidatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCandidatos.setText("Gestionar Candidatos");
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });

        btnElecciones.setBackground(new java.awt.Color(255, 51, 51));
        btnElecciones.setForeground(new java.awt.Color(255, 255, 255));
        btnElecciones.setText("Gestionar Elecciones");
        btnElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionesActionPerformed(evt);
            }
        });

        btnElecciones1.setBackground(new java.awt.Color(51, 102, 255));
        btnElecciones1.setForeground(new java.awt.Color(255, 255, 255));
        btnElecciones1.setText("Configurar Opciones de Elección");
        btnElecciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElecciones1ActionPerformed(evt);
            }
        });

        btn_Menu1.setBackground(new java.awt.Color(102, 102, 0));
        btn_Menu1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_Menu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Menu1.setText("← Regresar");
        btn_Menu1.setToolTipText("");
        btn_Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnElecciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnElecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElecciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Menu1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
       frmCandidatos ventanaCandidatos = new frmCandidatos();
       //Invoca al formulario
       ventanaCandidatos.setVisible(true);
        //Esto indica la posicion del formulario
       ventanaCandidatos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnCandidatosActionPerformed

    private void btnEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionesActionPerformed
      frmElecciones ventanaCandidatos = new frmElecciones();
       //Invoca al formulario
       ventanaCandidatos.setVisible(true);
        //Esto indica la posicion del formulario
       ventanaCandidatos.setLocationRelativeTo(null);
       dispose();
    }//GEN-LAST:event_btnEleccionesActionPerformed

    private void btnElecciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElecciones1ActionPerformed
     frmConfigurarElecciones ventanaCandidatos = new frmConfigurarElecciones();
       //Invoca al formulario
       ventanaCandidatos.setVisible(true);
        //Esto indica la posicion del formulario
       ventanaCandidatos.setLocationRelativeTo(null);
       dispose();
    }//GEN-LAST:event_btnElecciones1ActionPerformed

    private void btn_Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu1ActionPerformed
        Login ventanaLogin = new Login();
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btn_Menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnElecciones;
    private javax.swing.JButton btnElecciones1;
    private javax.swing.JButton btn_Menu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
